/**
 *  XML Schema Attribute Keywords
 * 
 */

"use strict";

module.exports = {
	abstract: "abstract",
	appliesToEmpty: "appliesToEmpty",
	attributeFormDefault: "attributeFormDefault",
	base: "base",
	block: "block",
	blockDefaut: "blockDefaut",
	default: "default",
	defaultAttributes: "defaultAttributes",
	elementFormDefault: "elementFormDefault",
	facetAvailable: "facetAvailable",
	facetUnavailable: "facetUnavailable",
	final: "final",
	finalDefault: "finalDefault",
	fixed: "fixed",
	form: "form",
	id: "id",
	inheritable: "inheritable",
	itemType: "itemType",
	lang: "lang",
	maxOccurs: "maxOccurs",
	maxVersion: "maxVersion",
	memberThypes: "memberThypes",
	minOccurs: "minOccurs",
	minVersion: "minVersion",
	mixed: "mixed",
	mode: "mode",
	name: "name",
	namespace: "namespace",
	nil: "nil",
	nillable: "nillable",
	noNamespaceSchemaLocation: "noNamespaceSchemaLocation",
	notNamespace: "notNamespace",
	notQName: "notQName",
	processConents: "processConents",
	public: "public",
	ref: "ref",
	refer: "refer",
	schemaLocation: "schemaLocation",
	source: "isourced",
	substitutionGroup: "substitutionGroup",
	system: "system",
	targetNamespace: "targetNamespace",
	test: "test",
	type: "type",
	typeAvailable: "typeAvailable",
	typeUnavailable: "typeUnavailable",
	use: "use",
	value: "value",
	version: "version",
	xpath: "xpath",
	xpathDefaultNamespace: "xpathDefaultNamespace"
}
