/**
 *  XML Schema Element Keywords
 * 
 */

"use strict";

module.exports = {
	all: "all",
	alternative: "alternative",
	annotation: "annotation",
	any: "any",
	anyAttribute: "anyAttribute",
	appinfo: "appinfo",
	assert: "assert",
	assertion: "assertion",
	attribute: "attribute",
	attributeGroup: "attributeGroup",
	choice: "choice",
	complexContent: "complexContent",
	complexType: "complexType",
	defaultOpenContent: "defaultOpenContent",
	documentation: "documentation",
	element: "element",
	enumeration: "enumeration",
	explicitTimezone: "explicitTimezone",
	extension: "extension",
	field: "field",
	fractionDigits: "fractionDigits",
	group: "group",
	import: "import",
	include: "include",
	key: "key",
	keyref: "keyref",
	length: "length",
	list: "list",
	maxExclusive: "maxExclusive",
	maxInclusive: "maxInclusive",
	maxLength: "maxLength",
	minExlusive: "minExlusive",
	minInclusive: "minInclusive",
	minLength: "minLength",
	notation: "notation",
	openContent: "openContent",
	override: "override",
	pattern: "pattern",
	redefine: "redefine",
	restriction: "restriction",
	schema: "schema",
	selector: "selector",
	sequence: "sequence",
	simpleContent: "simpleContent",
	simpleType: "simpleType",
	totalDigits: "totalDigits",
	union: "union",
	unique: "unique",
	whitespace: "whitespace"
}